/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author T480
 */
public class KonversiPanjang extends javax.swing.JFrame {

    /** Creates new form KonversiPanjang */
    public KonversiPanjang() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblJudul = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        txtValfrom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblF = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        txtValto = new javax.swing.JTextField();
        lblT = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbKilometerF = new javax.swing.JRadioButton();
        rbHektometerF = new javax.swing.JRadioButton();
        rbDekameterF = new javax.swing.JRadioButton();
        rbMeterF = new javax.swing.JRadioButton();
        rbDesimeterF = new javax.swing.JRadioButton();
        rbCentimeterF = new javax.swing.JRadioButton();
        rbMilimeterF = new javax.swing.JRadioButton();
        rbKilometerT = new javax.swing.JRadioButton();
        rbHektometerT = new javax.swing.JRadioButton();
        rbDekameterT = new javax.swing.JRadioButton();
        rbMeterT = new javax.swing.JRadioButton();
        rbDesimeterT = new javax.swing.JRadioButton();
        rbCentimeterT = new javax.swing.JRadioButton();
        rbMilimeterT = new javax.swing.JRadioButton();
        btnHitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setText("APLIKASI KONVERSI SATUAN PANJANG");

        lblFrom.setText("Kilometer");

        txtValfrom.setText("1");

        jLabel2.setText("=");

        lblF.setText("Km");

        lblTo.setText("Kilometer");

        txtValto.setText("1");

        lblT.setText("Km");

        jLabel6.setText("From");

        jLabel7.setText("To");

        buttonGroup1.add(rbKilometerF);
        rbKilometerF.setSelected(true);
        rbKilometerF.setText("Kilometer (Km)");
        rbKilometerF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKilometerFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbHektometerF);
        rbHektometerF.setText("Hektometer (Hm)");
        rbHektometerF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHektometerFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbDekameterF);
        rbDekameterF.setText("Dekameter (Dam)");
        rbDekameterF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDekameterFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbMeterF);
        rbMeterF.setText("Meter (M)");
        rbMeterF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMeterFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbDesimeterF);
        rbDesimeterF.setText("Desimeter (Dm)");
        rbDesimeterF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDesimeterFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCentimeterF);
        rbCentimeterF.setText("Centimeter (Cm)");
        rbCentimeterF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCentimeterFActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbMilimeterF);
        rbMilimeterF.setText("Milimeter (Mm)");
        rbMilimeterF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMilimeterFActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbKilometerT);
        rbKilometerT.setSelected(true);
        rbKilometerT.setText("Kilometer (Km)");
        rbKilometerT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbKilometerTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbHektometerT);
        rbHektometerT.setText("Hektometer (Hm)");
        rbHektometerT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHektometerTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbDekameterT);
        rbDekameterT.setText("Dekameter (Dam)");
        rbDekameterT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDekameterTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbMeterT);
        rbMeterT.setText("Meter (M)");
        rbMeterT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMeterTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbDesimeterT);
        rbDesimeterT.setText("Desimeter (Dm)");
        rbDesimeterT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDesimeterTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbCentimeterT);
        rbCentimeterT.setText("Centimeter (Cm)");
        rbCentimeterT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCentimeterTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbMilimeterT);
        rbMilimeterT.setText("Milimeter (Mm)");
        rbMilimeterT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMilimeterTActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lblJudul))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFrom)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtValfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblF)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(rbKilometerF)
                            .addComponent(rbHektometerF)
                            .addComponent(rbDekameterF)
                            .addComponent(rbMeterF)
                            .addComponent(rbDesimeterF)
                            .addComponent(rbCentimeterF)
                            .addComponent(rbMilimeterF))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtValto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblT))
                            .addComponent(jLabel7)
                            .addComponent(rbKilometerT)
                            .addComponent(rbHektometerT)
                            .addComponent(rbDekameterT)
                            .addComponent(rbMeterT)
                            .addComponent(rbDesimeterT)
                            .addComponent(rbCentimeterT)
                            .addComponent(rbMilimeterT)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnHitung)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblJudul)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFrom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(lblF)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblT))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbKilometerF)
                        .addGap(18, 18, 18)
                        .addComponent(rbHektometerF)
                        .addGap(18, 18, 18)
                        .addComponent(rbDekameterF)
                        .addGap(18, 18, 18)
                        .addComponent(rbMeterF)
                        .addGap(18, 18, 18)
                        .addComponent(rbDesimeterF)
                        .addGap(18, 18, 18)
                        .addComponent(rbCentimeterF)
                        .addGap(18, 18, 18)
                        .addComponent(rbMilimeterF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbKilometerT)
                        .addGap(18, 18, 18)
                        .addComponent(rbHektometerT)
                        .addGap(18, 18, 18)
                        .addComponent(rbDekameterT)
                        .addGap(18, 18, 18)
                        .addComponent(rbMeterT)
                        .addGap(18, 18, 18)
                        .addComponent(rbDesimeterT)
                        .addGap(18, 18, 18)
                        .addComponent(rbCentimeterT)
                        .addGap(18, 18, 18)
                        .addComponent(rbMilimeterT)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnHitung)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbKilometerFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKilometerFActionPerformed
    lblFrom.setText("Kilometer");
    lblF.setText("Km");
    }//GEN-LAST:event_rbKilometerFActionPerformed

    private void rbHektometerFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHektometerFActionPerformed
    lblFrom.setText("Hektometer");
    lblF.setText("Hm");
    }//GEN-LAST:event_rbHektometerFActionPerformed

    private void rbDekameterFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDekameterFActionPerformed
    lblFrom.setText("Dekameter");
    lblF.setText("Dam");
    }//GEN-LAST:event_rbDekameterFActionPerformed

    private void rbMeterFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMeterFActionPerformed
    lblFrom.setText("Meter");
    lblF.setText("M");
    }//GEN-LAST:event_rbMeterFActionPerformed

    private void rbDesimeterFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDesimeterFActionPerformed
    lblFrom.setText("Desimeter");
    lblF.setText("Dm");
    }//GEN-LAST:event_rbDesimeterFActionPerformed

    private void rbCentimeterFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCentimeterFActionPerformed
    lblFrom.setText("Centimeter");
    lblF.setText("Cm");
    }//GEN-LAST:event_rbCentimeterFActionPerformed

    private void rbMilimeterFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMilimeterFActionPerformed
    lblFrom.setText("Milimeter");
    lblF.setText("Mm");
    }//GEN-LAST:event_rbMilimeterFActionPerformed

    private void rbKilometerTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbKilometerTActionPerformed
    lblTo.setText("Kilometer");
    lblT.setText("Km");
    }//GEN-LAST:event_rbKilometerTActionPerformed

    private void rbHektometerTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHektometerTActionPerformed
    lblTo.setText("Hektometer");
    lblT.setText("Hm");
    }//GEN-LAST:event_rbHektometerTActionPerformed

    private void rbDekameterTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDekameterTActionPerformed
    lblTo.setText("Dekameter");
    lblT.setText("Dam");
    }//GEN-LAST:event_rbDekameterTActionPerformed

    private void rbMeterTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMeterTActionPerformed
    lblTo.setText("Meter");
    lblT.setText("M");
    }//GEN-LAST:event_rbMeterTActionPerformed

    private void rbDesimeterTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDesimeterTActionPerformed
    lblTo.setText("Desimeter");
    lblT.setText("Dm");
    }//GEN-LAST:event_rbDesimeterTActionPerformed

    private void rbCentimeterTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCentimeterTActionPerformed
    lblTo.setText("Centimeter");
    lblT.setText("Cm");
    }//GEN-LAST:event_rbCentimeterTActionPerformed

    private void rbMilimeterTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMilimeterTActionPerformed
    lblTo.setText("Milimeter");
    lblT.setText("Mm");
    }//GEN-LAST:event_rbMilimeterTActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
    try {
        double nilaiAwal = Double.parseDouble(txtValfrom.getText());
        
         // Cari satuan asal yang dipilih
        String satuanAsal = "";
        if (rbKilometerF.isSelected()) satuanAsal = "Km";
        else if (rbHektometerF.isSelected()) satuanAsal = "Hm";
        else if (rbDekameterF.isSelected()) satuanAsal = "Dam";
        else if (rbMeterF.isSelected()) satuanAsal = "M";
        else if (rbDesimeterF.isSelected()) satuanAsal = "Dm";
        else if (rbCentimeterF.isSelected()) satuanAsal = "Cm";
        else if (rbMilimeterF.isSelected()) satuanAsal = "Mm";
        
         // Cari satuan tujuan yang dipilih
        String satuanTujuan = "";
        if (rbKilometerT.isSelected()) satuanTujuan = "Km";
        else if (rbHektometerT.isSelected()) satuanTujuan = "Hm";
        else if (rbDekameterT.isSelected()) satuanTujuan = "Dam";
        else if (rbMeterT.isSelected()) satuanTujuan = "M";
        else if (rbDesimeterT.isSelected()) satuanTujuan = "Dm";
        else if (rbCentimeterT.isSelected()) satuanTujuan = "Cm";
        else if (rbMilimeterT.isSelected()) satuanTujuan = "Mm";
        
        // konversi panjangAwal ke meter dulu
        double panjangM = 0;
        panjangM = switch (satuanAsal) {
            case "Km" -> nilaiAwal * 1000;
            case "Hm" -> nilaiAwal * 100;
            case "Dam" -> nilaiAwal * 10;
            case "M" -> nilaiAwal;
            case "Dm" -> nilaiAwal / 10;
            case "Cm" -> nilaiAwal / 100;
            case "Mm" -> nilaiAwal / 1000;
            default -> nilaiAwal;
        };
        
        // konversi dari meter ke satuan tujuan
        double hasil = 0;
        hasil = switch (satuanTujuan) {
            case "Km" -> panjangM / 1000;
            case "Hm" -> panjangM / 100;
            case "Dam" -> panjangM / 10;
            case "M" -> panjangM;
            case "Dm" -> panjangM * 10;
            case "Cm" -> panjangM * 100;
            case "Mm" -> panjangM * 1000;
            default -> panjangM;
        };
         
        txtValto.setText(String.format("%.2f", hasil));
    } catch(NumberFormatException e) {
        txtValto.setText("Masukkan angka valid!");
    }
    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiPanjang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblF;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblT;
    private javax.swing.JLabel lblTo;
    private javax.swing.JRadioButton rbCentimeterF;
    private javax.swing.JRadioButton rbCentimeterT;
    private javax.swing.JRadioButton rbDekameterF;
    private javax.swing.JRadioButton rbDekameterT;
    private javax.swing.JRadioButton rbDesimeterF;
    private javax.swing.JRadioButton rbDesimeterT;
    private javax.swing.JRadioButton rbHektometerF;
    private javax.swing.JRadioButton rbHektometerT;
    private javax.swing.JRadioButton rbKilometerF;
    private javax.swing.JRadioButton rbKilometerT;
    private javax.swing.JRadioButton rbMeterF;
    private javax.swing.JRadioButton rbMeterT;
    private javax.swing.JRadioButton rbMilimeterF;
    private javax.swing.JRadioButton rbMilimeterT;
    private javax.swing.JTextField txtValfrom;
    private javax.swing.JTextField txtValto;
    // End of variables declaration//GEN-END:variables

}
